package exporters

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/lihd/chatgpt-math-exporter/internal/config"
)

type warningRecord struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func Run(cfg config.Config) error {
	if err := os.MkdirAll(cfg.Output.Dir, 0o755); err != nil {
		return fmt.Errorf("create output directory %q: %w", cfg.Output.Dir, err)
	}
	if err := os.MkdirAll(cfg.Output.AssetsDir, 0o755); err != nil {
		return fmt.Errorf("create assets directory %q: %w", cfg.Output.AssetsDir, err)
	}

	projectName := chooseProjectName(cfg)
	projectDir := filepath.Join(cfg.Output.Dir, slugify(projectName))
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return fmt.Errorf("create project directory %q: %w", projectDir, err)
	}

	if err := writePlaceholderConversation(filepath.Join(projectDir, "001_placeholder.md"), cfg, projectName); err != nil {
		return err
	}

	if cfg.Options.WriteReadme {
		if err := writeOutputReadme(filepath.Join(cfg.Output.Dir, "README.md"), cfg, projectName); err != nil {
			return err
		}
	}

	if cfg.Options.WriteWarnings {
		if err := writeWarnings(filepath.Join(cfg.Output.Dir, "warnings.json")); err != nil {
			return err
		}
	}

	return nil
}

func chooseProjectName(cfg config.Config) string {
	if cfg.Source.Project != "" {
		return cfg.Source.Project
	}
	switch cfg.Source.Type {
	case "bundle":
		return "chatgpt-export"
	case "project_url":
		return "chatgpt-project"
	default:
		return "export"
	}
}

func writePlaceholderConversation(path string, cfg config.Config, projectName string) error {
	content := fmt.Sprintf(`# %s

> Placeholder export generated by the current CGME project skeleton.

## Source

- Type: %s
- Bundle Path: %s
- Project URL: %s
- Generated At: %s

## Status

The Go project skeleton is ready, but real ChatGPT parsing and Markdown rendering have not been implemented yet.

## Next Step

The next implementation milestone should replace this placeholder with parsed conversation content from ChatGPT exports.
`,
		projectName,
		cfg.Source.Type,
		emptyFallback(cfg.Source.Path),
		emptyFallback(cfg.Source.ProjectURL),
		time.Now().Format(time.RFC3339),
	)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write placeholder markdown %q: %w", path, err)
	}
	return nil
}

func writeOutputReadme(path string, cfg config.Config, projectName string) error {
	content := fmt.Sprintf(`# CGME Export Output

This directory was generated by CGME.

## Summary

- Project: %s
- Source Type: %s
- Assets Directory: %s
- Preserve Links: %t

## Notes

- This output layout is intended to be reviewed locally and pushed to GitHub directly.
- The current implementation is a scaffold and writes placeholder Markdown for now.
`, projectName, cfg.Source.Type, cfg.Output.AssetsDir, cfg.Options.PreserveLinks)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write output README %q: %w", path, err)
	}
	return nil
}

func writeWarnings(path string) error {
	warnings := []warningRecord{
		{
			Code:    "skeleton.placeholder_export",
			Message: "This export was generated by the project skeleton. Real parsing and math normalization are not implemented yet.",
		},
	}

	data, err := json.MarshalIndent(warnings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal warnings: %w", err)
	}

	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("write warnings %q: %w", path, err)
	}
	return nil
}

func slugify(value string) string {
	s := strings.ToLower(strings.TrimSpace(value))
	s = strings.ReplaceAll(s, "_", "-")
	s = strings.ReplaceAll(s, " ", "-")
	s = regexp.MustCompile(`[^a-z0-9\-\p{Han}]`).ReplaceAllString(s, "")
	s = regexp.MustCompile(`-+`).ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == "" {
		return "export"
	}
	return s
}

func emptyFallback(value string) string {
	if value == "" {
		return "(not provided)"
	}
	return value
}
